import assert from 'node:assert/strict';
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
const browser = await chromium.launch({executablePath: process.env.BROWSER_EXECUTABLE, headless: true});
try {
  const page = await browser.newPage({viewport: {width: 1280, height: 900}});
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.route('http://127.0.0.1:8000/api/**', async route => {
    const response = await route.fetch({url: route.request().url().replace(':8000/', ':8001/')});
    await route.fulfill({response});
  });
  await page.goto(process.env.FLUTTER_URL || 'http://127.0.0.1:3002');
  await page.getByRole('button', {name: 'Edit reminder'}).first().waitFor({timeout: 60000});
  await page.getByRole('button', {name: 'Edit reminder'}).first().click();
  await page.getByRole('textbox', {name: 'Title', exact: true}).fill('Browser persistence check');
  await page.getByRole('button', {name: 'Save', exact: true}).click();
  await page.getByText('Reminder saved', {exact: true}).waitFor();
  await page.reload();
  await page.getByRole('button', {name: 'Edit reminder'}).first().waitFor({timeout: 30000});
  assert.match(await page.locator('body').ariaSnapshot(), /Browser persistence check/);
  assert.doesNotMatch(await page.locator('body').ariaSnapshot(), /\u00c2\u00b7/);
  console.log('PASS reminder edit survives browser reload through FastAPI/SQLite');
  await page.screenshot({path: 'docs/flutter-desktop.png', fullPage: true});
  await page.getByRole('button', {name: /Patient profile/}).click();
  await page.getByRole('menuitem', {name: 'Kamala Devi Sarma (Demo)', exact: true}).click();
  await page.getByRole('button', {name: 'Edit reminder'}).first().waitFor();
  assert.doesNotMatch(await page.locator('body').ariaSnapshot(), /Browser persistence check/);
  console.log('PASS switching patients keeps reminder records separate');
  await page.getByRole('button', {name: 'Games Tab 4 of 4'}).click();
  await page.getByRole('button', {name: 'Start word recall'}).click();
  await page.getByRole('button', {name: 'Check my words'}).waitFor();
  const savedResponse = page.waitForResponse(response => response.url().endsWith('/sessions') && response.request().method() === 'POST');
  await page.getByRole('button', {name: 'Check my words'}).click();
  const saved = await (await savedResponse).json();
  assert.equal(saved.score, 0);
  assert.equal(saved.errors, 3);
  await page.getByRole('button', {name: 'Play again'}).waitFor();
  assert.match(await page.locator('body').ariaSnapshot(), /0 of 3 words recalled/);
  await page.getByRole('button', {name: 'Play again'}).click();
  await page.getByRole('button', {name: 'Start word recall'}).waitFor();
  assert.match(await page.locator('body').ariaSnapshot(), /0% accuracy/);
  console.log('PASS actual word game saves zero accurately and reloads activity history');
  await page.setViewportSize({width: 390, height: 844});
  await page.getByRole('tab', {name: 'Today', exact: true}).click();
  await page.getByRole('button', {name: 'Edit reminder'}).first().waitFor();
  await page.screenshot({path: 'docs/flutter-mobile.png', fullPage: true});
  assert.deepEqual(errors, []);
  console.log('PASS desktop/mobile rendering without uncaught browser errors');
} finally { await browser.close(); }
