import { writeFileSync } from 'node:fs';
import { FEATURE_NAMES } from '../src/ml/riskFeatures';
let seed = 20260911;
const random = () => {seed = (Math.imul(seed,1664525)+1013904223)>>>0; return seed/4294967296;};
const clamp = (x:number,min:number,max:number) => Math.max(min,Math.min(max,x));
const classes = ['High','Low','Medium'];
const rows: {group:number;x:number[];y:number}[] = [];
for (let group=0;group<300;group++) {
  const ability = random();
  for(let i=0;i<4;i++) {
    const accuracy=clamp(30+ability*65+(random()-.5)*25,0,100);
    const response=clamp(8500-ability*6500+(random()-.5)*4000,500,15000);
    const errors=clamp((100-accuracy)/15+(random()-.5)*2,0,12);
    const days=Math.floor(random()*8);
    const std=random()*25;
    const level=1+Math.floor(random()*3);
    // Explicit toy activity rule. Labels are not diagnoses or clinical judgments.
    const support=(100-accuracy)*.65 + Math.min(response/1000,15)*2 + (7-days)*1.5 + std*.35;
    const label=support>=58?'High':support<35?'Low':'Medium';
    rows.push({group,x:[accuracy,response,errors,days,std,level],y:classes.indexOf(label)});
  }
}
// Hold out entire groups to prevent related rows appearing in both partitions.
const train=rows.filter(r=>r.group%5!==0), test=rows.filter(r=>r.group%5===0);
const mean=FEATURE_NAMES.map((_,j)=>train.reduce((s,r)=>s+r.x[j],0)/train.length);
const scale=FEATURE_NAMES.map((_,j)=>Math.sqrt(train.reduce((s,r)=>s+(r.x[j]-mean[j])**2,0)/train.length)||1);
const standard=(x:number[])=>x.map((v,j)=>(v-mean[j])/scale[j]);
const coef=classes.map(()=>FEATURE_NAMES.map(()=>0)), intercept=classes.map(()=>0);
const probabilities=(x:number[])=>{const z=coef.map((w,k)=>intercept[k]+w.reduce((s,v,j)=>s+v*x[j],0));const ex=z.map(v=>Math.exp(v-Math.max(...z)));return ex.map(v=>v/ex.reduce((a,b)=>a+b,0));};
for(let epoch=0;epoch<1800;epoch++) {
 const grad=coef.map(w=>w.map(()=>0)), bias=intercept.map(()=>0);
 for(const row of train) {const x=standard(row.x), p=probabilities(x); for(let k=0;k<3;k++){const error=p[k]-(row.y===k?1:0);bias[k]+=error;for(let j=0;j<x.length;j++)grad[k][j]+=error*x[j];}}
 for(let k=0;k<3;k++){intercept[k]-=.12*bias[k]/train.length;for(let j=0;j<mean.length;j++)coef[k][j]-=.12*(grad[k][j]/train.length+.001*coef[k][j]);}
}
const confusion=classes.map(()=>classes.map(()=>0));
for(const row of test) {const p=probabilities(standard(row.x));confusion[row.y][p.indexOf(Math.max(...p))]++;}
const correct=confusion.reduce((s,row,i)=>s+row[i],0);
const report={seed:20260911, dataset:'Synthetic toy activity support labels, not patient outcomes', labelRule:'0.65*(100-accuracy)+2*min(response_seconds,15)+1.5*(7-active_days)+0.35*accuracy_std; High >=58, Low <35, else Medium', trainRows:train.length,testRows:test.length,trainGroups:240,testGroups:60,split:'group % 5 === 0 held out; scaler fitted only on training data',classes,accuracy:correct/test.length,confusionMatrixActualRowsPredictedColumns:confusion,limitations:['Evaluation measures agreement with an authored toy rule on synthetic data.','It does not estimate dementia diagnosis accuracy or effectiveness in real people.','Feature distributions and thresholds require independent justification before use beyond a hackathon demonstration.']};
const weights={classes,features:FEATURE_NAMES,coef,intercept,scaler_mean:mean,scaler_scale:scale};
writeFileSync('src/ml/riskModelWeights.ts','// Generated by npm run train:model. See docs/model-evaluation.json.\nexport const RISK_MODEL_WEIGHTS = '+JSON.stringify(weights,null,2)+';\n');
writeFileSync('docs/model-evaluation.json',JSON.stringify(report,null,2)+'\n');
writeFileSync('docs/synthetic-model-data.json',JSON.stringify(rows)+'\n');
console.log(JSON.stringify(report,null,2));
