import React from 'react';
import { ResponsiveContainer, LineChart, Line, XAxis, YAxis, Tooltip, Legend, CartesianGrid } from 'recharts';
import type { GameSession, Language, TrendPoint } from '../../types';
import { choose, weeklyActivity } from '../../utils/activity';
export const CognitiveTrendChart = ({ data, sessions = [], language = 'en' }: { data: TrendPoint[]; sessions?: GameSession[]; language?: Language; showBenchmarks?: boolean }) => {
  const recorded = weeklyActivity(sessions);
  const labels = { memory: choose(language,'Word recall','शब्द स्मरण','শব্দ স্মৰণ'), attention: choose(language,'Pattern recall','पैटर्न स्मरण','আৰ্হি স্মৰণ'), executive: choose(language,'Picture matching','चित्र मिलान','ছবি মিলোৱা'), composite: choose(language,'All games','सभी खेल','সকলো খেল') };
  return <section className="bg-white rounded-2xl p-6 border border-[#E5E1D8] space-y-4">
    <h3 className="text-xl font-bold">{choose(language,'Weekly recorded activity','साप्ताहिक दर्ज गतिविधि','সাপ্তাহিক নথিভুক্ত কাৰ্যকলাপ')}</h3>
    <p className="text-sm text-[#73706A]">{choose(language,'Measured game accuracy, grouped by week starting Monday (UTC). Missing games have gaps. These are activity measures, not clinical domain scores.','खेल की मापी गई सटीकता, सोमवार से सप्ताह के अनुसार (UTC)। न खेले गए खेलों में अंतराल हैं। ये गतिविधि माप हैं, नैदानिक स्कोर नहीं।','খেলৰ জোখা শুদ্ধতা, সোমবাৰৰ পৰা সপ্তাহ অনুসৰি (UTC)। নেখেলা খেলত ফাঁক থাকে। এইবোৰ কাৰ্যকলাপৰ মাপ, ক্লিনিকেল স্কোৰ নহয়।')}</p>
    {recorded.length ? <div className="h-72"><ResponsiveContainer width="100%" height="100%"><LineChart data={recorded}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="week"/><YAxis domain={[0,100]}/><Tooltip/><Legend/>{Object.entries(labels).map(([key,label], i) => <Line key={key} dataKey={key} name={label} connectNulls={false} stroke={['#58745E','#426FAD','#AA712C','#7B518F'][i]} isAnimationActive={false}/>)}</LineChart></ResponsiveContainer></div> : <p>{choose(language,'Complete a game to start a dated activity history.','दिनांकित गतिविधि इतिहास शुरू करने के लिए एक खेल पूरा करें।','তাৰিখযুক্ত কাৰ্যকলাপৰ ইতিহাস আৰম্ভ কৰিবলৈ এটা খেল সম্পূৰ্ণ কৰক।')}</p>}
    {data.length > 0 && <details className="text-sm"><summary>{choose(language,'Imported demonstration / legacy history (excluded from recorded trends)','आयातित प्रदर्शन / पुराना इतिहास (दर्ज रुझानों से अलग)','আমদানিকৃত প্ৰদৰ্শন / পুৰণি ইতিহাস (নথিভুক্ত ধাৰাৰ পৰা পৃথক)')}</summary><p>{choose(language,`${data.length} existing historical points are retained in your backup. Their dates and measurement methods are unverified.`,`${data.length} पुराने बिंदु बैकअप में रखे गए हैं। उनकी तारीखें और माप विधियाँ सत्यापित नहीं हैं।`,`${data.length} টা পুৰণি তথ্যবিন্দু বেকআপত আছে। তাৰিখ আৰু মাপৰ পদ্ধতি যাচাই কৰা হোৱা নাই।`)}</p></details>}
  </section>;
};
